# Generated by Django 3.0.5 on 2020-05-03 22:20

import django.core.validators
import django.db.models.deletion
import django.utils.datetime_safe
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(default=django.utils.datetime_safe.datetime.now, verbose_name='date')),
                ('total_to_pay', models.FloatField(default=0, verbose_name='total to pay')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'bill',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('company_name', models.CharField(blank=True, max_length=50, verbose_name='company name')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('bank_account_information', models.CharField(blank=True, max_length=100, verbose_name='bank account information')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('internal_reference', models.CharField(blank=True, max_length=50, verbose_name='internal reference')),
                ('sell_price', models.FloatField(default=0, verbose_name='sell price')),
                ('buy_price', models.FloatField(default=0, verbose_name='buy price')),
                ('client_taxes_percentage', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='client taxes percentage')),
                ('internal_notes', models.CharField(blank=True, max_length=200, verbose_name='internal notes')),
                ('image', models.ImageField(default='product/default_image.png', upload_to='product', verbose_name='image')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mortuary.Provider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'product',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastname')),
                ('document', models.IntegerField(verbose_name='document')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('payment_address', models.CharField(max_length=50, verbose_name='payment address')),
                ('assigned_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='assigned vendor')),
                ('products', models.ManyToManyField(to='mortuary.Product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'client',
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='notes')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount')),
                ('price', models.FloatField(verbose_name='price')),
                ('taxes_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='taxes percentage')),
                ('subtotal', models.FloatField(default=0, verbose_name='subtotal')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortuary.Bill', verbose_name='bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mortuary.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'bill line',
            },
        ),
        migrations.CreateModel(
            name='ProviderBill',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortuary.Bill')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mortuary.Provider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'provider bill',
                'verbose_name_plural': 'provider bills',
            },
            bases=('mortuary.bill',),
        ),
        migrations.CreateModel(
            name='ClientBill',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortuary.Bill')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mortuary.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'client bill',
            },
            bases=('mortuary.bill',),
        ),
    ]
