# Generated by Django 3.0.5 on 2020-05-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortuary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='products',
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_products',
            field=models.ManyToManyField(null=True, to='mortuary.Product', verbose_name='assigned products'),
        ),
    ]
