# Generated by Django 3.0.5 on 2020-05-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortuary', '0002_auto_20200508_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='assigned_products',
            field=models.ManyToManyField(blank=True, to='mortuary.Product', verbose_name='assigned products'),
        ),
    ]
