# Generated by Django 3.0.5 on 2020-05-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortuary', '0003_auto_20200508_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
